import type { Metadata } from "next";
import "./globals.css";
import { clashDisplay, clashGrotesk, geistSans, kronaOne, nataSans } from "./_fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${clashDisplay.className} ${geistSans.variable} ${kronaOne.variable} ${clashGrotesk.variable} ${clashDisplay.variable} ${nataSans.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
